const express = require("express");
const router = express.Router();
const {getAllStudents,getStudent,updateStudent,deleteStudent,createStudent,getMyProfile, updateMyProfile} = require("../controllers/studentController");
const authMiddleware = require("../middleware/authMiddleware");
const roleMiddleware = require("../middleware/roleMiddleware");
router.post("/",authMiddleware, roleMiddleware(["admin"]), createStudent);
router.get("/",authMiddleware,roleMiddleware(["admin","faculty"]),getAllStudents);
router.get("/profile",authMiddleware,roleMiddleware(["student"]),getMyProfile);
router.patch("/profile",authMiddleware,roleMiddleware(["student"]),updateMyProfile);
router.patch("/:id",authMiddleware, roleMiddleware(["admin"]),updateStudent);
router.delete("/:id",authMiddleware, roleMiddleware(["admin"]),deleteStudent);
router.get("/:id",authMiddleware, roleMiddleware(["admin","faculty"]),getStudent);
module.exports = router;
